---
- assert:
    that: "ansible_distribution_major_version is version_compare('8', '>=')"
    msg: "AlmaLinux version supported"
#- debug: var=ansible_distribution_major_version

- name: install RedHat common packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ gitlab_dependencies }}"

- name: install AlmaLinux packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - policycoreutils

# gitlab_dependencies includes openssh-server and postfix,
# so ensure they're enabled and running
- name: start postfix and sshd
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - postfix
    - sshd

- name: start firewalld
  service:
    name: firewalld
    enabled: true
    state: started

# firewalld has migrated to the community posix collection 
# which can be installed with ansible-galaxy
#    ansible-galaxy collection install ansible.posix
# use command instead even if this isn't idempotent
- name: enable firewalld http and https
  command: firewall-cmd --permanent --add-service="{{ item }}"
  args:
    warn: no
  register: firewall
  loop:
    - http
    - https
#- debug: var=firewall

- name: reload firewalld
  command: firewall-cmd --reload
  args:
    warn: no
  register: reload
#- debug: var=reload
