---
- assert:
    that: "ansible_distribution_major_version is version_compare('7', '>=')"
    msg: "CentOS version supported"
#- debug: var=ansible_distribution_major_version

- name: install CentOS packages
  package:
    name: postfix
    state: present

- name: start postfix
  service:
    name: postfix
    enabled: true
    state: started

- name: start sshd and firewalld
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - sshd
    - firewalld

# firewalld has migrated to the community posix collection 
# which can be installed with ansible-galaxy
#    ansible-galaxy collection install ansible.posix
# use command instead even if this isn't idempotent
- name: enable firewalld http and https
  command: firewall-cmd --permanent --add-service="{{ item }}"
  args:
    warn: no
  register: firewall
  loop:
    - http
    - https
#- debug: var=firewall

- name: reload firewalld
  command: firewall-cmd --reload
  args:
    warn: no
  register: reload
#- debug: var=reload
