---
- assert:
    that: "ansible_distribution_major_version is version_compare('9', '>=')"
    msg: "Debian version supported"
#- debug: var=ansible_distribution_major_version

- name: install Debian packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ gitlab_dependencies }}"

- name: start postfix and sshd
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - postfix
    - sshd

# run the repo install script
# install the gitlab package