---
- assert:
    that: "ansible_distribution_major_version is version_compare('9', '>=')"
    msg: "Debian version supported"
#- debug: var=ansible_distribution_major_version

- name: install Debian packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ gitlab_dependencies }}"

- name: start postfix and sshd
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - postfix
    - sshd

- name: set LOCALE
  block:
    - copy:
        dest: /etc/default/locale
        content: >
          LANG=NONE
        mode: 0644
        owner: root
        group: root
    - replace:
        path: /etc/locale.gen
        backup: yes
        regexp: '^# (en_US.UTF-8 UTF-8)'
        replace: '\1'
    - command: locale-gen
      args:
        warn: no
      register: locale_gen
- debug: var=locale_gen.stdout_lines


# don't use EXTERNAL_URL environment variable because the ssl certs will be wrong
# set gitlab_domain variable in playbook instead
- name: Install GitLab (this will take a while)
  shell: >
    apt-get install -y "{{ gitlab_package_name | default(gitlab_edition) }}" > "{{ gitlab_install_log }}"
  args:
    warn: false
#    creates: "{{ gitlab_install_log }}"
  when: not gitlab_file.stat.exists
  ignore_errors: True
  register: gitlab_install
#  check_mode: yes
- debug: 
    var: gitlab_install.stderr_lines
  when: gitlab_install|selectattr("stderr_lines", "defined")|list|length >0
