---
- assert:
    that: "ansible_distribution_major_version is version_compare('16', '>=')"
    msg: "Ubuntu version supported"
#- debug: var=ansible_distribution_major_version


- name: install Ubuntu packages
  package:
    name: postfix
    state: present

- name: start postfix
  service:
    name: postfix
    enabled: true
    state: started
