---
- assert:
    that: "ansible_distribution_major_version is version_compare('18', '>=')"
    msg: "Ubuntu version supported"
#- debug: var=ansible_distribution_major_version

- name: install Ubuntu packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ gitlab_dependencies }}"

- name: start postfix and sshd
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - postfix
    - sshd

# specifically because AWS sets the hostname to ip-xxx-xxx-xxx-xxx.REGION.compute.internal
- name: set hostname on AWS
  lineinfile:
    path: /etc/hostname
    regexp: 'ip.*.compute.internal'
    line: "{{ inventory_hostname }}"
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: is_aws_environment

# don't use EXTERNAL_URL environment variable because the ssl certs will be wrong
# set gitlab_domain variable in playbook instead
- name: Install GitLab (this will take a while)
  shell: >
    apt-get install -y "{{ gitlab_package_name | default(gitlab_edition) }}" > \
    "{{ gitlab_install_log }}"
  args:
    warn: false
#    creates: "{{ gitlab_install_log }}"
  when: not gitlab_file.stat.exists
  ignore_errors: True
  register: gitlab_install
#  check_mode: yes
- debug:
    var: gitlab_install.stderr_lines
  when: gitlab_install|selectattr("stderr_lines", "defined")|list|length >0
