---
- assert:
    that: "ansible_distribution_major_version is version_compare('16', '>=')"
    msg: "Ubuntu version supported"
#- debug: var=ansible_distribution_major_version

- name: install Ubuntu packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ gitlab_dependencies }}"

- name: start postfix and sshd
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - postfix
    - sshd
