# playbook for load balancer hosts
# this will install both roles, then run the handlers for both roles
---
- hosts: lbr
  become: true
  roles:
    - role: ansible-role-common
    - role: ansible-role-haproxy

  # geerlingguy's module doesn't do everything, so pick up the slack
  tasks:
    - name: additional haproxy setup
      import_tasks: haproxy_tasks.yml

  handlers:
   - name: restart haproxy
     service: 
       name: haproxy 
       state: restarted
   - name: restart rsyslog
     service: 
       name: rsyslog
       state: restarted
