# playbook for apache in gitlab server hosts
# this will install both roles, then run the handlers for both roles
# ansible should pull variables from group_vars/glservers anyway
---
- hosts: glservers

  vars_files:
    - group_vars/glservers
  become: true

  roles:
    - role: ansible-role-common

    #  submodule git@github.com:geerlingguy/ansible-role-apache.git
    - role: ansible-role-apache
      vars:
        apache_listen_port: 80
        apache_vhosts:
        - servername: "{{ ansible_hostname }}"
          documentroot: /var/www/html
          extra_parameters: |
            RewriteCond %{HTTP_HOST} !^www\. [NC]
            RewriteRule ^(.*)$ http://www.%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

  tasks:
    - name: enhance welcome message
      replace:
        path: /usr/share/httpd/noindex/index.html
        regexp: '<h1>(Testing 123..)</h1>'
        replace: '<h1>\1<br>on {{ ansible_hostname }}</h1>'
        backup: yes
