# gitlab site playbook for multiple installs
---
#============================================================================== all
# do the common installed stuff first so handlers for it run 
# before a node-specific role is run with it's own handlers
#
- hosts: gitlab gitlab_py3
  become: true
  # check_mode: yes  # yes=dry-run
  roles:
    - gitlab
  vars:
    gitlab_domain: "{{ ansible_hostname }}.aws-vilain.com"
    gitlab_external_url: "https://{{ gitlab_domain }}/"

#============================================================================== lbr
- hosts: lbr
  become: true
  roles:
  - haproxy
