# defaults file for haproxy
---
haproxy_socket: /var/lib/haproxy/stats
haproxy_chroot: /var/lib/haproxy

# haproxy running under "root" because
# Vagrant+virtual box won't forword port 80
haproxy_user: haproxy
haproxy_group: haproxy

# Frontend settings.
haproxy_frontend_name: 'hafrontend'
haproxy_frontend_bind_address: '*'
haproxy_frontend_port: 80
haproxy_frontend_mode: 'http'

# Backend settings.
haproxy_backend_name: 'habackend'
haproxy_backend_mode: 'http'

# Balancing Algorithm. Available options: roundrobin, source, leastconn, source, uri
# (if persistance is required use, "source")
haproxy_backend_balance_method: 'roundrobin'

# check will fail with default welcome page in apache as "HEAD /" returns "forbidden"
#haproxy_backend_httpchk: 'HEAD / HTTP/1.1\r\nHost:localhost'
haproxy_backend_httpchk: ""

# List of backend servers.
haproxy_backend_servers: []
# - name: app1
#   address: 192.168.0.1:80
# - name: app2
#   address: 192.168.0.2:80

# Extra global vars (see README for example usage).
haproxy_global_vars: []
