---
gitlab_package_version_separator: '='
gitlab_repo_script_url: "https://packages.gitlab.com/install/repositories/gitlab/{{ gitlab_edition }}/script.deb.sh"
gitlab_dependencies: 
  - curl
  - openssh-server
  - ca-certificates
  - perl
